### ISSUE TITLE
Scrubs V2 is not working in TMDB Players

### ISSUE THREAD

**Issue by ashwamegh** [jewbmx/repo#21]
Hi @jewbmx 

I have Scrubs v2 and The Crew installed and I am using both the plugins using TMDB players. Well, The Crew is working but not the Scrubs V2. I tried debugging the logs and multiple fixes. This is the error which gets coming up

```
2023-05-25 00:16:48.400 T:375442    info <general>: [plugin.video.themoviedb.helper]
                                                   lib.player - finished resolving path to url
                                                   plugin://plugin.video.scrubsv2/?action=play&title=John+Wick:+Chapter+4&year=2023&imdb=tt10366206&t=20230525001646371407

2023-05-25 00:16:53.014 T:375436    info <general>: [plugin.video.themoviedb.helper]
                                                   ConnectionTimeOut: HTTPSConnectionPool(host='www.omdbapi.com', port=443): Read timed out. (read timeout=15)
2023-05-25 00:17:14.172 T:375829   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'simplejson.errors.JSONDecodeError'>
                                                   Error Contents: Expecting value: line 1 column 1 (char 0)
                                                   Traceback (most recent call last):
                                                     File "/Users/twinklesinha/Library/Application Support/Kodi/addons/script.module.simplejson/lib/simplejson/scanner.py", line 37, in _scan_once
                                                       nextchar = string[idx]
                                                                  ~~~~~~^^^^^
                                                   IndexError: string index out of range

                                                   During handling of the above exception, another exception occurred:

                                                   Traceback (most recent call last):
                                                     File "/Users/twinklesinha/Library/Application Support/Kodi/addons/plugin.video.scrubsv2/main.py", line 7, in <module>
                                                       system.router(argv[2])
                                                     File "/Users/twinklesinha/Library/Application Support/Kodi/addons/plugin.video.scrubsv2/resources/lib/system.py", line 46, in router
                                                       sources.sources().addItem(title)
                                                     File "/Users/twinklesinha/Library/Application Support/Kodi/addons/plugin.video.scrubsv2/resources/lib/modules/sources.py", line 823, in addItem
                                                       meta = json.loads(meta)
                                                              ^^^^^^^^^^^^^^^^
                                                     File "/Users/twinklesinha/Library/Application Support/Kodi/addons/script.module.simplejson/lib/simplejson/__init__.py", line 525, in loads
                                                       return _default_decoder.decode(s)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/Users/twinklesinha/Library/Application Support/Kodi/addons/script.module.simplejson/lib/simplejson/decoder.py", line 370, in decode
                                                       obj, end = self.raw_decode(s)
                                                                  ^^^^^^^^^^^^^^^^^^
                                                     File "/Users/twinklesinha/Library/Application Support/Kodi/addons/script.module.simplejson/lib/simplejson/decoder.py", line 400, in raw_decode
                                                       return self.scan_once(s, idx=_w(s, idx).end())
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/Users/twinklesinha/Library/Application Support/Kodi/addons/script.module.simplejson/lib/simplejson/scanner.py", line 79, in scan_once
                                                       return _scan_once(string, idx)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/Users/twinklesinha/Library/Application Support/Kodi/addons/script.module.simplejson/lib/simplejson/scanner.py", line 39, in _scan_once
                                                       raise JSONDecodeError(errmsg, string, idx)
                                                   simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   -->End of Python script error report<--

2023-05-25 00:17:14.365 T:375827   error <general>: GetDirectory - Error getting plugin://plugin.video.scrubsv2/?action=add_item&title=John+Wick%3A+Chapter+4
2023-05-25 00:17:14.371 T:291053   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.scrubsv2/?action=add_item&title=John+Wick%3A+Chapter+4) failed
2023-05-25 00:17:14.430 T:291053   error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.themoviedb.helper/?info=play&tmdb_type=movie&tmdb_id=603692]
```

I am not sure, is this plugin error or the player's 

The players which I am using for TMDB are located here: https://github.com/mrgsi/tmdbh.players

More specifically the JSON config is here: https://github.com/mrgsi/tmdbh.players/blob/master/direct.scrubsv2.json

Can you please check if anything you can do on your side to fix it?

**Comment by jewbmx** [comment]
Your problem is the player file.
Try using the one i uploaded around a month back, its in atleast two locations on here.
Id also suggest telling the proper folks about this since they are the ones that supplied you with a bad file. 
(I installed that dumb addon and tossed in your player file, got the same error, then tossed my version of the file in and it worked perfectly. Altho your file didn't pop up a extra popup box like mine does.

Oh and while your at it maybe tell the person that maintains tmdbhelper that they need to update their addon for the setInfo stuff, got like 60 lines in the debug log that says they suck balls 🙄

**Comment by jewbmx** [comment]
i played around a bit and added my player file to the github.io url lol

it can now be seen in the normal url as it was before with the repo installs.
plus  https://jewbmx.github.io/tmdbh.players/
or  https://jewbmx.github.io/tmdbh.players/direct.scrubsv2.json

no clue tho if any of these ways help folks out :) i dont actually use the addon that uses these players lol.

**Comment by jewbmx** [comment]
opps clicked close on this issue lmao
